############################################
#   .---.  .----. .-. .-..----..-. .---.   #
#  /  ___}/  {}  \|  `| || {_  | |/   __}  #
#  \     }\      /| |\  || |   | |\  {_ }  #
#   `---'  `----' `-' `-'`-'   `-' `---'   #
############################################

announceAdvancements:
  overworld: true
  nether: true
  end: true

########################################################
#  .----..-.  .-.  .--.  .-.   .-..----. .-.   .----.  #
#  | {_   \ \/ /  / {} \ |  `.'  || {}  }| |   | {_    #
#  | {__  / /\ \ /  /\  \| |\ /| || .--' | `--.| {__   #
#  `----'`-'  `-'`-'  `-'`-' ` `-'`-'    `----'`----'  #
########################################################

# exampleGamerule1: (Booleans)
#   overworld: true
#   nether: false
#   end: false

# exampleGamerule2: (Integers)
#   overworld: 50
#   nether: 100
#   end: 150